--1. Find all persons with their department name & code.

	SELECT P.PERSONNAME,D.DEPARTMENTNAME,D.DEPARTMENTCODE FROM PERSON AS P INNER JOIN DEPARTMENT AS D 
		ON P.DEPARTMENTID = D.DEPARTMENTID
 
--2. Give department wise maximum & minimum salary with department name.

	SELECT D.DEPARTMENTNAME,MAX(P.SALARY),MIN(P.SALARY) FROM PERSON AS P INNER JOIN DEPARTMENT AS D 
		ON P.DEPARTMENTID = D.DEPARTMENTID 
		GROUP BY D.DEPARTMENTNAME

--3. Find all departments whose total salary is exceeding 100000.

	SELECT D.DEPARTMENTNAME,SUM(P.SALARY) FROM PERSON AS P INNER JOIN DEPARTMENT AS D
		ON P.DEPARTMENTID = D.DEPARTMENTID
		GROUP BY D.DEPARTMENTNAME
		HAVING SUM(P.SALARY)>100000 

--4. Retrieve person name, salary & department name who belongs to Jamnagar city.

	SELECT P.PERSONNAME,P.SALARY,D.DEPARTMENTNAME FROM PERSON AS P INNER JOIN DEPARTMENT AS D
		ON P.DEPARTMENTID = D.DEPARTMENTID
		WHERE P.CITY = 'JAMNAGAR'

--5. Find all persons who does not belongs to any department.

	SELECT P.PERSONNAME,D.DEPARTMENTNAME FROM PERSON AS P LEFT OUTER JOIN DEPARTMENT AS D
		ON P.DEPARTMENTID = D.DEPARTMENTID
		WHERE P.DEPARTMENTID IS NULL

--6. Find department wise person counts.

	SELECT D.DEPARTMENTNAME,COUNT(P.PERSONID) FROM PERSON AS P INNER JOIN DEPARTMENT AS D 
		ON P.DEPARTMENTID = D.DEPARTMENTID
		GROUP BY D.DEPARTMENTNAME  

--7. Find average salary of person who belongs to Ahmedabad city.

	SELECT AVG(SALARY) FROM PERSON WHERE CITY = 'AHMEDABAD'

--8. Produce Output Like: <PersonName> earns <Salary> from department <DepartmentName> monthly.(In single column)

	SELECT P.PERSONNAME + ' EARNS ' + CAST(P.SALARY AS VARCHAR(10)) + ' FROM DEPARTMENT ' + D.DEPARTMENTNAME + ' MONTHLY '
	 FROM PERSON AS P INNER JOIN DEPARTMENT AS D
		ON P.DEPARTMENTID = D.DEPARTMENTID

--9. List all departments who have no persons.

	SELECT D.DEPARTMENTNAME,P.PERSONNAME FROM PERSON AS P LEFT OUTER JOIN DEPARTMENT AS D
		ON P.DEPARTMENTID = D.DEPARTMENTID
		WHERE P.PERSONNAME IS NULL

--10. Find city & department wise total, average & maximum salaries.

	SELECT SUM(SALARY),AVG(SALARY),MAX(SALARY) FROM PERSON
		GROUP BY CITY

	SELECT D.DEPARTMENTNAME,SUM(P.SALARY),AVG(P.SALARY),MAX(P.SALARY) FROM PERSON AS P INNER JOIN DEPARTMENT AS D
		ON P.DEPARTMENTID = D.DEPARTMENTID
		GROUP BY D.DEPARTMENTNAME

--11. Display Unique city names.

	SELECT DISTINCT(CITY) FROM PERSON

--12. List out department names in which more than two persons.

	SELECT D.DEPARTMENTNAME,COUNT(P.PERSONNAME) FROM PERSON AS P INNER JOIN DEPARTMENT AS D
		ON P.DEPARTMENTID = D.DEPARTMENTID
		GROUP BY D.DEPARTMENTNAME
		HAVING COUNT(P.PERSONNAME)>2 

--13. Combine person name’s first three characters with city name’s last three characters in single column.

	SELECT LEFT(PERSONNAME,3) + RIGHT(CITY,3) FROM PERSON 

--14. Give 10% increment in Computer department employee’s salary.

	SELECT SALARY+(SALARY/10) FROM PERSON 
	WHERE DEPARTMENTID =(SELECT DEPARTMENTID FROM DEPARTMENT WHERE DEPARTMENTNAME = 'COMPUTER')  

--15. Display all the person name’s who’s joining dates difference with current date is more than 365 days.	SELECT PERSONNAME,JOININGDATE FROM PERSON  WHERE GETDATE()-JOININGDATE>365	