-----STORE_PROCEDURE-----

--Give proper name like PR_TableName_OperationName

--1. Select All (CityID, CityName, Pincode, CityRemarks, StateID,StateName)

	--PR_MST_CITY_SELECTALL

	CREATE PROCEDURE PR_MST_CITY_SELECTALL

	AS
	BEGIN

	SELECT C.CITYID,C.CITYNAME,C.PINCODE,C.CITYREMARKS,S.STATEID,S.STATENAME
	FROM MST_CITY AS C INNER JOIN MST_STATE AS S 
	ON C.STATEID = S.STATEID

	END

	EXEC PR_MST_CITY_SELECTALL

--2. Insert

	--PR_MST_CITY_INSERT

	CREATE PROCEDURE PR_MST_CITY_INSERT

	@CITYID				INT,
	@CITYNAME			VARCHAR(50),
	@PINCODE			VARCHAR(6),
	@STATEID			INT,
	@CITYREMARKS		VARCHAR(250)

	AS
	BEGIN

	INSERT INTO MST_CITY VALUES

	(@CITYID,@CITYNAME,@PINCODE,@STATEID,@CITYREMARKS)

	END

	EXEC PR_MST_CITY_INSERT 2,RAJKOT,360004,1,AVERAGE

--3. Update

	--PR_MST_CITY_UPDATE

	CREATE PROCEDURE PR_MSR_CITY_UPDATE

	@CITYID				INT,
	@CITYNAME			VARCHAR(50),
	@PINCODE			VARCHAR(50),
	@STATEID			INT,
	@CITYREMARKS		VARCHAR(250)

	AS
	BEGIN

	UPDATE MST_CITY

	SET		CITYNAME	=	@CITYNAME,
			PINCODE		=	@PINCODE,
			STATEID		=	@STATEID,
			CITYREMARKS	=	@CITYREMARKS
	WHERE	CITYID		=	@CITYID

	END

	EXEC	PR_MSR_CITY_UPDATE 2,RAJKOT,360005,1,GOOD

--4. Delete

	--PR_MST_CITY_DELETE

	CREATE PROCEDURE PR_MST_CITY_DELETE

	@CITYID		INT

	AS
	BEGIN

	DELETE FROM MST_CITY WHERE
		CITYID = @CITYID

	END

	EXEC PR_MST_CITY_DELETE 2

--5. SelectByPK

	--PR_MST_CITY_SELECTBYPK

	CREATE PROCEDURE PR_MST_CITY_SELECTBYPK

	@CITYID		INT

	AS
	BEGIN

	SELECT * FROM MST_CITY
		WHERE CITYID = @CITYID

	END

	EXEC PR_MST_CITY_SELECTBYPK 2

--6. SelectByPincodeStartWith360

	--PR_MST_CITY_SELECTBYPINCODESTARTSWITH360

	CREATE PROCEDURE PR_MST_CITY_SELECTBYPINCODESTARTSWITH360

	AS
	BEGIN

	SELECT * FROM MST_CITY
	WHERE PINCODE LIKE '360%'

	END

	EXEC PR_MST_CITY_SELECTBYPINCODESTARTSWITH360 

--7. SelectByCityNamePincode

	--PR_MST_CITY_SELECTBYCITYNAMEPINCODE

	CREATE PROCEDURE PR_MST_CITY_SELECTBYCITYNAMEPINCODE

	@CITYNAME VARCHAR(50) , @PINCODE VARCHAR(6)

	AS
	BEGIN

	SELECT * FROM MST_CITY
	WHERE CITYNAME = @CITYNAME AND PINCODE = @PINCODE

	END

	EXEC PR_MST_CITY_SELECTBYCITYNAMEPINCODE RAJKOT,360001

--8. SelectByCityRemarks

	--PR_MST_CITY_SELECTBYCITYREMARKS

	CREATE PROCEDURE PR_MST_CITY_SELECTBYCITYREMARKS
	
	@CITYREMARKS VARCHAR(250)

	AS
	BEGIN

	SELECT * FROM MST_CITY
	WHERE CITYREMARKS = @CITYREMARKS

	END

	EXEC PR_MST_CITY_SELECTBYCITYREMARKS VERYGOOD

--9. SelectByStateID

	--PR_MST_CITY_SELECTBYSTATEID

	CREATE PROCEDURE PR_MST_CITY_SELECTBYSTATEID
	
	@STATEID INT

	AS
	BEGIN

	SELECT * FROM MST_CITY
	WHERE STATEID = @STATEID

	END

	
	EXEC  PR_MST_CITY_SELECTBYSTATEID 1

--10. SelectByStateIDCityID

	--PR_MST_CITY_SELECTBYSTATEIDCITYID

	CREATE PROCEDURE PR_MST_CITY_SELECTBYSTATEIDCITYID
	
	@STATEID INT, @CITYID INT

	AS
	BEGIN

	SELECT * FROM MST_CITY
	WHERE STATEID = @STATEID AND CITYID = @CITYID

	END

	EXEC  PR_MST_CITY_SELECTBYSTATEIDCITYID 1,1
	